// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlaB2C_xDs1VQCP1wwv7TjAPi0JugnY8Y',
    appId: '1:517853377290:web:6fb1ba571ddd6e38e000f3',
    messagingSenderId: '517853377290',
    projectId: 'pawlly-474f0',
    authDomain: 'pawlly-474f0.firebaseapp.com',
    storageBucket: 'pawlly-474f0.firebasestorage.app',
    measurementId: 'G-E8PGER4VXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZYoZ1fT1pz0oOi-hjYwkN2VEo9IRQBv8',
    appId: '1:517853377290:android:1feacfca588445b6e000f3',
    messagingSenderId: '517853377290',
    projectId: 'pawlly-474f0',
    storageBucket: 'pawlly-474f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJPJDLRV8tKNjC9QSXEzBl9x-ocfnWKg',
    appId: '1:517853377290:ios:54cb8e81f5b24346e000f3',
    messagingSenderId: '517853377290',
    projectId: 'pawlly-474f0',
    storageBucket: 'pawlly-474f0.firebasestorage.app',
    iosBundleId: 'com.pawlly.employee',
  );
}
